from fixtures import PLATFORM, CUP_R, CUP_L, CUP_C, NARROW_TUB_BUG
from s import World

import pytest


def test_from_scan(capfd):
    world = World.from_scan(open('./ex').read(), (500, 0))
    world.show()
    out, err = capfd.readouterr()
    assert out.strip() == '''
..................
..................
..................
........+.........
........|.....#...
...#..#.......#...
...#..#..#........
...#..#..#........
...#.....#........
...#.....#........
...#######........
..................
..................
......#.....#.....
......#.....#.....
......#.....#.....
......#######.....
..................
..................
..................
    '''.strip()

def test_spread_and_spill(capfd):
    world = World.from_ascii_art(PLATFORM)
    for _ in range(9):
        world.step()
    world.show()
    out, err = capfd.readouterr()
    assert out.strip() == '''
..............
..............
..............
.......+......
.......|......
.......|......
...||||||||...
...|######|...
..............
..............
..............
    '''.strip()

def test_fill_and_spill(capfd):
    world = World.from_ascii_art(CUP_R)
    for _ in range(40):
        world.step()
    world.show()
    out, err = capfd.readouterr()
    assert out.strip() == '''
...................
...................
...................
..........+........
..........|........
...|||||||||||||...
...|#~~~~~~~~~#|...
...|#~~~~~~~~~#|...
...|#~~~~~~~~~#|...
...|#~~~~~~~~~#|...
...|###########|...
...................
...................
...................
    '''.strip()

def test_fill_and_spill_2(capfd):
    expected = '''
...|||||||||||||...
...|#~~~~~~~~~#|...
...|#~~~~~~~~~#|...
...|#~~~~~~~~~#|...
...|#~~~~~~~~~#|...
...|###########|...
    '''.strip()

    world = World.from_ascii_art(CUP_R)
    for _ in range(40):
        world.step()
    world.show()
    out, err = capfd.readouterr()
    assert '\n'.join(out.strip().splitlines()[5:11]) == expected

    world = World.from_ascii_art(CUP_L)
    for _ in range(40):
        world.step()
    world.show()
    out, err = capfd.readouterr()
    assert '\n'.join(out.strip().splitlines()[5:11]) == expected

    world = World.from_ascii_art(CUP_C)
    for _ in range(40):
        world.step()
    world.show()
    out, err = capfd.readouterr()
    assert '\n'.join(out.strip().splitlines()[5:11]) == expected

def test_narrow_tub_bug(capfd):
    world = World.from_ascii_art(NARROW_TUB_BUG)
    for _ in range(100):
        world.step()
    world.show()
    out, err = capfd.readouterr()
    assert out.strip() == '''
...........................
...........................
...........................
..........+................
..........|................
..........|................
..........|................
...#......|............#...
...#|||||||||||||......#...
...#~~~~~~~~~#~#|......#...
...#~~~~~~~~~#~#|......#...
...#~~~~~~~~~#~#~~~~~~~#...
...#~~~~~~~~~#~#~~~~~~~#...
...#~~~~~~~~~###~~~~~~~#...
...#~~~~~~~~~~~~~~~~~~~#...
...#~~~~~~~~~~~~~~~~~~~#...
...#####################...
...........................
...........................
...........................
    '''.strip()

def test_count_water():
    world = World.from_scan(open('./ex').read(), (500, 0))
    for _ in range(100):
        world.step()
    assert world.count_water() == 57
